services:
  traefik:
    command:
      - "--providers.docker=true"
      - "--api.dashboard=true"
      - "--api.insecure=false"
      - "--log.level=WARN"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http3"
      - "--certificatesresolvers.myresolver.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"  # for HTTP/3 UDP traffic
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.${DOMAIN_BASE}`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=${DASHBOARD_AUTH}"
      - "traefik.http.routers.dashboard.tls.certresolver=myresolver"

  external-ws-proxy:
    image: nginxinc/nginx-unprivileged:stable-alpine
    expose:
      - "80"
    networks:
      - app-network
    volumes:
      - ./.docker/go-chat/proxy.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.ws-phpqa.rule=HostSNI(`ws.phpqa.ru`)"
      - "traefik.tcp.routers.ws-phpqa.entrypoints=websecure"
      - "traefik.tcp.routers.ws-phpqa.tls=true"
      - "traefik.tcp.routers.ws-phpqa.tls.certresolver=myresolver"
      - "traefik.tcp.routers.ws-phpqa.service=ws-phpqa-service"
      - "traefik.tcp.services.ws-phpqa-service.loadbalancer.server.port=80"

  php-fpm:
    labels:
      - "traefik.enable=true"
      # HTTP
      - "traefik.http.routers.phpqa-http.rule=Host(`phpqa.ru`)"
      - "traefik.http.routers.phpqa-http.entrypoints=web"
      - "traefik.http.routers.phpqa-http.service=phpqa"
      # HTTPS
      - "traefik.http.routers.phpqa.rule=Host(`phpqa.ru`) || Host(`www.phpqa.ru`)"
      - "traefik.http.routers.phpqa.entrypoints=websecure"
      - "traefik.http.routers.phpqa.tls.certresolver=myresolver"

      - "traefik.http.routers.phpqa.service=phpqa"
      - "traefik.http.services.phpqa.loadbalancer.server.port=80"

      # Compress
      - "traefik.http.routers.phpqa.middlewares=php-compress"
      - "traefik.http.middlewares.php-compress.compress=true"
      - "traefik.http.middlewares.php-compress.compress.includedcontenttypes=text/html,text/plain,text/css,application/javascript,application/json"

    networks:
      - app-network

  pets-app:
    volumes:
      - /var/www/pets.phpqa.ru/app:/app:rw
    labels:
      - "traefik.enable=true"
      # HTTP to HTTPS redirect
      - "traefik.http.routers.pets-http.rule=Host(`pets.phpqa.ru`)"
      - "traefik.http.routers.pets-http.entrypoints=web"
      #      - "traefik.http.routers.pets-http.middlewares=pets-https-redirect"
      #      - "traefik.http.middlewares.pets-https-redirect.redirectscheme.scheme=https"
      # HTTPS configuration
      - "traefik.http.routers.pets-secure.rule=Host(`pets.phpqa.ru`)"
      - "traefik.http.routers.pets-secure.entrypoints=websecure"
      - "traefik.http.routers.pets-secure.tls=true"
      - "traefik.http.routers.pets-secure.tls.certresolver=myresolver"
      - "traefik.http.services.pets.loadbalancer.server.port=80"
    networks:
      - app-network

  sveltewar-app:
    build:
      context: /var/www/sveltewar.phpqa.ru/html/
      dockerfile: Dockerfile
    volumes:
      - /var/www/sveltewar.phpqa.ru/html/public:/usr/share/nginx/html/:rw
    labels:
      - "traefik.enable=true"
      # HTTP to HTTPS redirect
      - "traefik.http.routers.sveltewar-http.rule=Host(`sveltewar.phpqa.ru`)"
      - "traefik.http.routers.sveltewar-http.entrypoints=web"
      #      - "traefik.http.routers.sveltewar-http.middlewares=sveltewar-https-redirect"
      #      - "traefik.http.middlewares.sveltewar-https-redirect.redirectscheme.scheme=https"
      # HTTPS configuration
      - "traefik.http.routers.sveltewar-secure.rule=Host(`sveltewar.phpqa.ru`)"
      - "traefik.http.routers.sveltewar-secure.entrypoints=websecure"
      - "traefik.http.routers.sveltewar-secure.tls=true"
      - "traefik.http.routers.sveltewar-secure.tls.certresolver=myresolver"
      - "traefik.http.services.sveltewar.loadbalancer.server.port=80"
    networks:
      - app-network
