services:
  traefik:
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.ws.address=:8080"
    ports:
      - "80:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=web"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/var/www:/var/www:rw"

  php-fpm:
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.phpqa.loadbalancer.server.port=80"
      - "traefik.http.routers.phpqa.entrypoints=web"
      - "traefik.http.routers.phpqa.rule=Host(`phpqa.local`)"
      # WebSocket configuration for development
      - "traefik.http.routers.phpqa-ws.rule=Host(`phpqa.local`) && PathPrefix(`/ws`)"
      - "traefik.http.routers.phpqa-ws.entrypoints=ws"
      - "traefik.http.services.ws-service.loadbalancer.server.port=8010"
    expose:
      - "80"
    networks:
      - app-network

  pets-app:
    build:
      context: app/.docker
      dockerfile: php-fpm/Dockerfile
    volumes:
      - /var/www/pets.phpqa.ru:/var/www/pets.phpqa.ru:rw
      - /var/www:/var/www
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pets.rule=Host(`pets.local`)"
      - "traefik.http.routers.pets.entrypoints=web"
      - "traefik.http.services.pets.loadbalancer.server.port=9000"
      - "traefik.http.middlewares.pets-strip.stripprefix.prefixes=/var/www/pets.phpqa.ru/app/public"
    networks:
      - app-network

  sveltewar-app:
    build:
      context: /var/www/my.fb.admin/var/www/sveltewar.phpqa.ru/html/
      dockerfile: Dockerfile
    volumes:
      - /var/www/sveltewar.phpqa.ru/public:/usr/share/nginx/html/:rw
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sveltewar.rule=Host(`sveltewar.local`)"
      - "traefik.http.routers.sveltewar.entrypoints=web"
      - "traefik.http.services.sveltewar.loadbalancer.server.port=9000"
      - "traefik.http.middlewares.sveltewar-strip.stripprefix.prefixes=/var/www/sveltewar.phpqa.ru/html/public"
    networks:
      - app-network

#  mailer:
#    image: mailhog/mailhog
#    environment:
#      MAILER_HOST: ${MAILER_HOST}
#      MAILER_PORT: ${MAILER_PORT}
#      MAILER_USER: ${MAILER_USER}
#      MAILER_PASSWORD: ${MAILER_PASSWORD}
#      MAILER_ENCRYPTION: ${MAILER_ENCRYPTION}
#      MAILER_FROM_EMAIL: ${MAILER_FROM_EMAIL}
#    ports:
#      - "1025:1025"
#      - "8025:8025"
#    networks:
#      - app-network
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.mailhog.rule=Host(`mail.localhost`)"
#      - "traefik.http.routers.mailhog.entrypoints=web"
#      - "traefik.http.services.mailhog.loadbalancer.server.port=8025"
