version: '3'
services:
  nginx:
    build:
      context: docker/nginx
    volumes:
      - ./:/var/www/phpqa.ru/html
      - ./storage/logs/nginx:/var/log/nginx/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php-fpm-lara
    networks:
      - internal

  php-fpm-lara:
    build:
      context: docker/php-7.4-fpm-alpine
    volumes:
      - ./:/var/www/phpqa.ru/html
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal"
      PHP_IDE_CONFIG: "serverName=Docker-my-phpqa"
    networks:
      - internal
    links:
      - mysql-lara
    depends_on:
      - mysql-lara

  mysql-lara:
    image: mysql:8
    container_name: mysql-lara
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - ./docker/mysql/db_data:/var/lib/mysql:rw
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    command: --default-authentication-plugin=mysql_native_password
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'my.laravel.blog'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'root'
      ## Use % to allow remote access to all addresses.
      ## Generally not recommended by some people to allow for root.
      MYSQL_ROOT_HOST: "0.0.0.0"

  myadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql-lara
    restart: always
    depends_on:
      - mysql-lara


networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28
