version: '3'
services:
    web:
        image: nginx:alpine
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/ssl:/etc/ssl"
            - "./app:/var/www/phpqa.ru/app"
            - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
        ports:
            - "8079:80"
            - "3000:443"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
#        restart: always
        depends_on:
            - php-fpm
            - mysql-db
        networks:
            static-network:
                ipv4_address: 172.20.0.71

    php-fpm:
        build:
            context: docker/php-8.0-fpm-alpine
        volumes:
            - "./app:/var/www/phpqa.ru/app"
        environment:
            XDEBUG_CONFIG: "remote_host=wsl.host remote_port=9003"
            PHP_IDE_CONFIG: serverName=Docker
        networks:
            static-network:
                ipv4_address: 172.20.0.10

#    adminer:
#        image: adminer
#        restart: always
#        ports:
#            - "8081:8080"
#        networks:
#            static-network:
#                ipv4_address: 172.20.0.73

    mysql-db:
        image: mysql:${MYSQL_VERSION}
        #restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "8989:3306"
        volumes:
            - "./data/db/mysql/my.cnf:/etc/mysql/conf.d/my.cnf"
            - "./data/db/mysql/db_data:/var/lib/mysql"
#            - mysql-data:/var/lib/mysql
        networks:
            static-network:
                ipv4_address: 172.20.0.77

#    pg-db:
#        image: postgres:${POSTGRES_VERSION}
##        restart: always
#        env_file:
#            - ".env"
#        environment:
#            - POSTGRES_DB=${POSTGRES_DB}
#            - POSTGRES_USER=${POSTGRES_USER}
#            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#        ports:
#            - "5432:5432"
#        volumes:
#            - pgdata:/var/lib/postgresql/data

#    myadmin:
#        image: phpmyadmin/phpmyadmin:fpm-alpine
#        container_name: phpmyadmin
#        ports:
#            - "8080:80"
#        environment:
#            - PMA_ARBITRARY=1
#            - PMA_HOST=${MYSQL_HOST}
#        restart: always
#        depends_on:
#            - mysqldb

#volumes:
#    mysql-data:
#        external: true

networks:
    static-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.20.0.0/28
