version: "3.9"
services:
    gateway:
        build:
            context: gateway/.docker
            dockerfile: common/nginx/Dockerfile
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt:ro
            - /etc/ssl:/etc/ssl:ro
            - /var/www:/var/www:ro
            # Копируем все сайты из родительской системы в докер образ Nginx
            - /etc/nginx/sites-available:/etc/nginx/conf.d:rw
        ports:
            - ${GATEWAY_HOTS_PORT}:${GATEWAY_DOCKER_PORT}
            - "443:443"
            - "8084:8084"
            - "8083:8083"

    phpqa-nginx:
        build:
            context: app/.docker
            dockerfile: common/nginx/Dockerfile
        volumes:
            - ./app:/app

    php-fpm:
        build:
            context: app/.docker
            dockerfile: common/php-fpm/Dockerfile
        container_name: php-fpm
        environment:
#            APP_ENV: ${APP_ENV}
#            APP_DEBUG: ${APP_DEBUG}
            PHP_IDE_CONFIG: serverName=${SERVER_NAME}
            DB_HOST: ${DB_HOST}
            DB_USER: ${MYSQL_ROOT_USER}
            DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            DB_NAME: ${MYSQL_DATABASE}
            MAILER_HOST: ${MAILER_HOST}
            MAILER_PORT: ${MAILER_PORT}
            MAILER_USER: ${MAILER_USER}
            MAILER_PASSWORD: ${MAILER_PASSWORD}
            MAILER_ENCRYPTION: ${MAILER_ENCRYPTION}
            MAILER_FROM_EMAIL: ${MAILER_FROM_EMAIL}
            SENTRY_DSN: ${SENTRY_DSN}
        volumes:
            - ./app:/app

    php-fpm-for-all:
        build:
            context: app/.docker
            dockerfile: common/php-fpm/Dockerfile
        container_name: php-fpm-for-all
        volumes:
            - /var/www:/var/www:rw
            - ./app:/app

    mysql:
        image: mysql:${MYSQL_VERSION}
        container_name: ${DB_HOST}
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        volumes:
            - "./data/db/mysql/my.cnf:/etc/mysql/conf.d/my.cnf"
            - "./data/db/mysql/db_data:/var/lib/mysql"
        ports:
            - "8989:3306"
        security_opt:
            - seccomp:unconfined

    node:
        build:
            context: app/.docker/node
        container_name: node-phpqa
        volumes:
            - ./app:/app
