---
-   name: Install Docker SDK dependencies
    apt:
        name:
            - python3-pip
            - virtualenv
            - python-setuptools
#            - python-docker
            - python3-docker
        state: present
        update_cache: yes

